version: '3.9'

services:
  client:
    image: alokverma20/client-app
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:4000

  server:
    image: alokverma20/server-app
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
